#cloud-config
groups:
    - ubuntu
users:
    - default
    - name: ubuntu
      primary-group: ubuntu
      groups: users
      sudo: ALL=NOPASSWD:ALL
      passwd: ubuntu
apt_sources:
    - source: "ppa:cloud-installer/ppa"
    - source: "ppa:maas-maintainers/stable"
packages:
    - maas
    - maas-dhcp
    - maas-dns
    - vlan
