#cloud-config

write_files:
  - content: |
      #!/bin/sh
      mkdir -p /dev/net || true
      mknod /dev/kvm c 10 232
      mknod /dev/net/tun c 10 200
      exit 0
    path: /etc/rc.local
    permissions: '0755'
packages:
  - software-properties-common
{% if extra_pkgs %}
{% for pkg in extra_pkgs %}
  - {{ pkg }}
{% endfor %}
{% endif %}
groups:
  - libvirtd: [ubuntu]
  - sudo: [ubuntu]
apt_get_wrapper:
  command: eatmydata
  enabled: auto
apt_sources:
  - source: "ppa:cloud-installer/testing"
{% if extra_ppa %}
{% for ppa in extra_ppa %}
  - source: "{{ ppa }}"
{% endfor %}
{% endif %}
{% if extra_sshkeys %}
ssh_authorized_keys:
{% for ssh in extra_sshkeys %}
  - {{ ssh }}
{% endfor %}
{% endif %}
random_seed:
  command: {{seed_command}}
{% if apt_mirror %}
apt_mirror: {{apt_mirror}}
{% endif %}
package_update: true
password: ubuntu
chpasswd: { expire: False }
ssh_pwauth: True
manage_etc_hosts: localhost


# Make sure we load our modules on first creation
runcmd:
  - [ sh, /etc/rc.local ]
  - echo "export PATH=$PATH:/usr/sbin" >> /home/ubuntu/.bashrc
{% if http_proxy %}
  - echo "export http_proxy={{ http_proxy }}" >> /home/ubuntu/.bashrc
  - echo "export HTTP_PROXY={{ http_proxy }}" >> /home/ubuntu/.bashrc
{% endif %}
{% if https_proxy %}
  - echo "export https_proxy={{ https_proxy }}" >> /home/ubuntu/.bashrc
  - echo "export HTTPS_PROXY={{ https_proxy }}" >> /home/ubuntu/.bashrc
{% endif %}
